### ISSUE TITLE
[bug] describe the bug

### ISSUE THREAD

**Issue by iijiang** [fubarhouse/pygmy#370]
Windows 11, 
WSL 2
 Ubuntu 20.04.3 LTS

`uname -a`
`Linux DESKTOP-3N7M3LQ 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

Copied pygmy-linux-amd64-static as executable.
`cp ./builds/pygmy-linux-amd64-static /usr/local/bin/pygmy;`

`pygmy status`

```
[ ] amazeeio-mailhog is not able to start on port 1025: listen tcp :1025: bind: address already in use

[ ] amazeeio-mailhog is not running
[ ] Resolv Linux Resolver is not properly connected
```
`pygmy up`
```
[ ] amazeeio-mailhog is not able to start on port 1025: listen tcp :1025: bind: address already in use
Please address the above issues before you attempt to start Pygmy again.
```

**Comment by fubarhouse** [comment]
This one was handled away from GitHub and privately. For reference, the resolution was stopping the old pygmy containers.

Perhaps we can consider adding detection for  legacy pygmy containers? Though it's really arbitrary - pygmy does not know about legacy-pygmy containers other than the container names - this is kind of a big assumption. I'm not completely sold on the implementation as it's very unlikely people will run this along side legacy more than once.

**Comment by iijiang** [comment]
Thanks Karl. I would think its better to get the lines in README, although readme didnt really mention `gem uninstall pygmy` or `pygmy down` first.
