### ISSUE TITLE
[feature] Alias `stop` for `down`

### ISSUE THREAD

**Issue by bomoko** [fubarhouse/pygmy#398]
Currently, we can call `up` and `start` to bring up pygmy-go.
Start was introduced to bring pygmy-go to parity with pygmy legacy, however, the corresponding "stop" doesn't seem to have been introduced.

In pygmy legacy, the semantics of `down` and `stop` are slightly different (`stop` has a `destroy` flag). But they're not _that_ different. It would be good if we could introduce a "stop" alias in order to at least have symmetry in up/down and start/stop.

**Describe the solution you'd like**

I'd like to be able to call "pygmy-go stop" and have it bring pygmy down.

**Describe alternatives you've considered**

The alternative I've considered is arguing that we should remove `pygmy start`.

**Comment by fubarhouse** [comment]
I've added a slightly more fleshed out stop command in #400 - which does a little more than just aliasing to `down`.
Let me know which direction you prefer, and we can go with that.

**Comment by bomoko** [comment]
@fubarhouse - nicely done!

Yeah, this brings it in line with the legacy, yours is way better (mine was literally "damnit, I typed `pygmy-go stop` again and it didn't work, what's the quickest way to make that not the case?").
PR makes perfect sense as well!

**Comment by fubarhouse** [comment]
Perfect.

I'll work toward merging it and I can revisit the whole start/up thingy later, it would be good to make it clear and purposeful now that stop is in the mix of it.
