### ISSUE TITLE
[feature] Command to update uselagoon base images

### ISSUE THREAD

**Issue by rocketeerbkw** [fubarhouse/pygmy#478]
**Is your feature request related to a problem? Please describe.**

If you want to update all the base images used in a project, you have to either 1) delete all local images or 2) manually run `docker pull` for each image.

**Describe the solution you'd like**

Create a new command or change `pygmy update` to search for all local `uselagoon/*` images and automatically `docker pull` them.

**Describe alternatives you've considered**

Document how to do this manually.

**Additional context**

This was a [feature in pygmy-legacy](https://github.com/pygmystack/pygmy-legacy/blob/50082121cfff735e8fce00862e071365b6036572/lib/pygmy/amazee.rb) that didn't get duplicated.

**Comment by fubarhouse** [comment]
I've added a loop in the update command to include `uselagoon/*` images in the local registry.
Feel free to test #479 and let me know.
