### ISSUE TITLE
Pygmy Podman and MacOS

### ISSUE THREAD

**Issue by rsau** [fubarhouse/pygmy#532]
Hi 

I tried Podman on MacOS 14.3.1 after a long time because I am having issues with Colima 
Pygmy starts without any issues but DNS is broken. 

Have you tested Pygmy with Podman?

Thanks

**Comment by fubarhouse** [comment]
Podman works a little bit differently - but I am glad everything starts.
Some extra work may be required for DNS.

My recommendation would be to try to delete the resolv file and re-test.
Please let me know how that goes, I am very interested in increasing compatibility.

I have found some nuance on bare metal with Colima to the same effect - it might be worth providing additional logic to exclude the resolv files on specific configurations.

**Comment by rsau** [comment]
> My recommendation would be to try to delete the resolv file and re-test. 

I did that based on previous experience but unfortunately it didn't help. 
Back on Colima. I'll try Podman next week

> I am very interested in increasing compatibility 

Let me know how I can help.

**Comment by rsau** [comment]
So I tried Rancher Desktop as well to see if there are any issues

It is working fine

![image](https://github.com/pygmystack/pygmy/assets/29110027/d2f99db4-f0b3-4baf-9ad9-d569181ec9d9)

**Comment by fubarhouse** [comment]
Fantastic, good to know.

I did try to force pygmy to use Podman last night, but no such luck.
Pygmy does use the Docker SDK, so compatibility with Podman might not be a short-term thing...

**Comment by rsau** [comment]
Just like Colima, I had to run `sudo rm /etc/resolver/docker.amazee.io` for Rancher Desktop as well.
